version: '3.3'
services:
  db:
    container_name: 'margetasDb'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  wordpress:
    container_name: 'margetasWp'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"
#      - *@3YKp&vQvgb(t@3C)
#  filewatcher:
#    container_name: watcher
#    build:
#      context: wordpress/wp-content/themes/GiannisMargetas/Filewatcher/
#    volumes:
#      - "./wordpress/wp-content/themes/GiannisMargetas:/usr/app/Server"
  adminDb:
    image: phpmyadmin:latest
    container_name: phpadminMargetas
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: somewordpress
      PMA_USER: root
